route:
  group_by: ["alertname"]
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 365d
  receiver: "web.hook"
  routes:
  - receiver: "empty"
    match:
      alertname: Watchdog
  - receiver: "web.hook"
receivers:
  - name: "empty"
  - name: "web.hook"
    webhook_configs:
      - url: "http://localhost:8081/alerts/handler"
        send_resolved: true
